FROM ubuntu:18.04
MAINTAINER author "vizdl@qq.com"
ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /workdir
RUN	apt-get update
RUN	apt-get install git bc bison flex libssl-dev make -y
RUN apt-get install gcc-aarch64-linux-gnu -y